# Generated by Django 5.2 on 2025-05-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='veiculo/fotos'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.SmallIntegerField(choices=[(1, 'AMARELO'), (2, 'VERDE'), (3, 'AZUL'), (4, 'PRATA'), (5, 'PRETO'), (6, 'VERMELHO')]),
        ),
    ]
